// Generated by CoffeeScript 1.8.0
(function() {
  var app, cheerio, express, request, sites;

  cheerio = require('cheerio');

  express = require('express');

  request = require('request');

  app = express();

  app.set('port', process.env.PORT || 5000);

  sites = {
    musixmatch: 'https://www.musixmatch.com/lyrics/'
  };

  app.get('/:sitename/:artist/:title', function(req, res) {
    var prms, url;
    prms = req.params;
    if (prms.sitename === 'musixmatch') {
      url = sites[prms.sitename] + [prms.artist, prms.title].join('/');
    }
    return request(url, function(error, response, body) {
      var $, text;
      $ = cheerio.load(body);
      text = $('#lyrics-html').text();
      return res.json({
        response: text
      });
    });
  });

  app.get('*', function(req, res) {
    return res.json({
      error: 'not enough params'
    });
  });

  app.listen(app.get('port'), function() {
    return console.log("Node app is running at localhost: " + (app.get('port')));
  });

}).call(this);
